# configs/strategy_morbido.yaml
pivot_mode: floor
thresholds:
  funding_neutral_max: 0.0
  funding_bull_min: 0.00015
  oi_drop_pct: 3.0
  oi_rise_pct: 3.0
  liquidations_usd_15m: 120000000
  cvd_window_min: 40
  vwap_min_distance_pct: 0.15
  whales_ratio_min_change_pct: 5.0
  min_bull_reasons: 2
  min_bear_reasons: 2
  margin_buy_min: 15
  margin_sell_min: 15
  breakout_confirm_candles: 2
  donchian_window: 20
bear_weights:
  funding_neutral_or_neg: 10
  oi_drop: 15
  liq_spike_mean_revert: 25
  cvd_negative: 15
  break_pivot_down: 20
  whales_net_selling: 10
  vwap_below: 12
  break_vwap_down: 18
bull_weights:
  funding_positive: 10
  oi_rise: 15
  cvd_positive: 15
  break_pivot_up: 20
  whales_net_buying: 10
  vwap_above: 12
  break_vwap_up: 18
decision:
  sell_score: 60
  buy_score: 60